name: "Deploy to aws"

on: workflow_dispatch

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: "checkout the code"
              uses: action/checkout@v2
    
            - name: "setup nodejs"
              uses: action/setup-nodejs@v4
              with: 
                node-version:"21"
    
            - name: "Install dependencies"
              run: npm install

            - name: "install pm2 globally"
              run: npm install pm2 -g
    
            - name: "run tests"
              run: npm run test
    
            - name: "Deploy to aws"
              run: pm2 start src/index.js
