name: "Deploy to AWS"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21" 

      - name: "Install dependencies"
        run: npm install

      - name: "Install PM2 globally"
        run: npm install -g pm2

      - name: "Run tests"
        run: npm run test

      - name: "Deploy to AWS using PM2"
        run: pm2 start src/index.js 

